# Generated by Django 5.0.4 on 2024-04-27 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='requested_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_currency', to='payapp.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_currency', to='payapp.currency'),
        ),
    ]
