# Generated by Django 5.0.4 on 2024-04-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_invoice_sender_id_alter_payee_sender_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='currency_id',
        ),
    ]
