# Generated by Django 5.0.4 on 2024-04-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
