# Generated by Django 5.0.4 on 2024-04-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payees',
            new_name='Payee',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
