# Generated by Django 5.0.4 on 2024-04-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_rename_payees_payee_rename_roles_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('iso_code', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=5)),
                ('curr_rate', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
    ]
