# Generated by Django 5.0.4 on 2024-04-29 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0006_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='invoice_id',
            new_name='invoice',
        ),
    ]
