# Generated by Django 5.0.4 on 2024-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0009_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
