# Generated by Django 5.0.4 on 2024-04-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0012_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.CharField(choices=[('1', 'Read'), ('0', 'Unread')], default='0', max_length=1),
        ),
    ]
