# Generated by Django 5.0.4 on 2024-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0013_alter_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction_status',
            field=models.CharField(choices=[('1', 'Paid'), ('2', 'Rejected'), ('0', 'Not paid')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('1', 'Paid'), ('0', 'Not paid'), ('2', 'Rejected')], default='0', max_length=1),
        ),
    ]
